// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CalculateIndicator(arg1:string):Promise<string>;

export function ExecutePythonScript(arg1:string,arg2:string):Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetAvailableIndicators():Promise<Array<string>>;

export function GetStockData(arg1:string):Promise<Array<model.KLine>>;

export function GetSystemInfo():Promise<Record<string, any>>;
