// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateIndicator(arg1) {
  return window['go']['main']['App']['CalculateIndicator'](arg1);
}

export function ExecutePythonScript(arg1, arg2) {
  return window['go']['main']['App']['ExecutePythonScript'](arg1, arg2);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetAvailableIndicators() {
  return window['go']['main']['App']['GetAvailableIndicators']();
}

export function GetStockData(arg1) {
  return window['go']['main']['App']['GetStockData'](arg1);
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}
